
/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2011     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/

//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file contains the PV class for pingpong.
//* This is a template file: You may modify this file to implement the 
//* behavior of your component. 
//* 
//* Model Builder version: 3.1.1
//* Generated on: Aug. 08, 2011 07:55:08 AM, (user: jon)
//* Automatically merged on: Aug. 16, 2011 04:43:45 PM, (user: jon)
//* Automatically merged on: Sep. 26, 2011 07:41:20 AM, (user: jon)
//* Automatically merged on: Jan. 09, 2012 02:04:29 PM, (user: jon)
//* Automatically merged on: Jan. 20, 2012 09:12:44 AM, (user: jon)
//*>


#pragma once

#include "pingpong_model.h"

using namespace tlm;

class pingpong_pv;
typedef bool (pingpong_pv::*wFuncType) (esl::tlm_types::Address, unsigned char*, unsigned);

//This class inherits from the pingpong_pv_base class
class pingpong_pv : public pingpong_pv_base {
 public:
  typedef esl::tlm_types::Address mb_address_type;
 public:
  // Constructor
  // Do not add parameters here.
  // To add parameters - use the Model Builder form (under PV->Parameters tab)
  SC_HAS_PROCESS(pingpong_pv);
  pingpong_pv(sc_core::sc_module_name module_name);   

  void thread();

 protected:
  ////////////////////////////////////////
  // target ports read callbacks
  //////////////////////////////////////// 
  bool d1_callback_read(mb_address_type address, unsigned char* data, unsigned size);
  unsigned d1_callback_read_dbg(mb_address_type address, unsigned char* data, unsigned size);
  bool d2_callback_read(mb_address_type address, unsigned char* data, unsigned size);
  unsigned d2_callback_read_dbg(mb_address_type address, unsigned char* data, unsigned size); 

 protected:
  ////////////////////////////////////////
  // target ports write callbacks
  //////////////////////////////////////// 
  bool d1_callback_write(mb_address_type address, unsigned char* data, unsigned size);
  unsigned d1_callback_write_dbg(mb_address_type address, unsigned char* data, unsigned size);
  bool d1_get_direct_memory_ptr(mb_address_type address, tlm::tlm_dmi& dmiData);
  bool d2_callback_write(mb_address_type address, unsigned char* data, unsigned size);
  unsigned d2_callback_write_dbg(mb_address_type address, unsigned char* data, unsigned size);
  bool d2_get_direct_memory_ptr(mb_address_type address, tlm::tlm_dmi& dmiData);  

 private:
  sc_event m1ev, m2ev;
  int m1todo, m2todo;
  unsigned int m1count, m2count;
  unsigned int m1addr, m2addr;
};


