
/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2015     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/

//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file contains the PV class for AXI_SLAVE.
//* This is a template file: You may modify this file to implement the 
//* behavior of your component. 
//* 
//* Model Builder version: 4.2.2beta
//* Generated on: Nov. 24, 2016 04:47:30 PM, (user: markca)
//*>



#include "AXI_SLAVE_pv.h"
#include <iostream>
#include <bitset>

using namespace sc_core;
using namespace sc_dt;
using namespace std;

//constructor
AXI_SLAVE_pv::AXI_SLAVE_pv(sc_module_name module_name) 
  : AXI_SLAVE_pv_base(module_name) {
}      

// Read callback for slave port.
// Returns true when successful.
bool AXI_SLAVE_pv::slave_callback_read(mb_address_type address, unsigned char* data, unsigned size) {
  cout << name() << " @ " << sc_time_stamp() << " READ from address = " << address << endl;
  
  return true;
}

// Write callback for slave port.
// Returns true when successful.
bool AXI_SLAVE_pv::slave_callback_write(mb_address_type address, unsigned char* data, unsigned size) {
  std::string binary = std::bitset<32>((unsigned int) *data).to_string(); //to binary
  unsigned int val = (unsigned int) *data;
  cout << name() << " @ " << sc_time_stamp() << " WRITE to address " << address << " data = " << hex << val << " , " << binary << endl;
  
  return true;
} 




unsigned AXI_SLAVE_pv::slave_callback_read_dbg(mb_address_type address, unsigned char* data, unsigned size) {
  return 0;
} 

unsigned AXI_SLAVE_pv::slave_callback_write_dbg(mb_address_type address, unsigned char* data, unsigned size) {
  return 0;
} 

bool AXI_SLAVE_pv::slave_get_direct_memory_ptr(mb_address_type address, tlm::tlm_dmi& dmiData) {
  return false;
}

 

// in order to minimize merging conflicts, we recommend to add your functions after this comment
