
/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2012     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/

//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file contains the PV class for APB32_16.
//* This is a template file: You may modify this file to implement the 
//* behavior of your component. 
//* 
//* Model Builder version: 3.4.0
//* Generated on: Jul. 04, 2012 04:27:13 PM, (user: markca)
//* Automatically merged on: Jul. 04, 2012 04:28:10 PM, (user: markca)
//* Automatically merged on: Nov. 20, 2012 02:12:49 PM, (user: markca)
//*>


#pragma once

#include "APB32_16_model.h"

using namespace tlm;

//This class inherits from the APB32_16_pv_base class
class APB32_16_pv : public APB32_16_pv_base {
 public:
  typedef esl::tlm_types::Address mb_address_type;
 public:
  // Constructor
  // Do not add parameters here.
  // To add parameters - use the Model Builder form (under PV->Parameters tab)
  SC_HAS_PROCESS(APB32_16_pv);
  APB32_16_pv(sc_core::sc_module_name module_name);   

 protected:
  ////////////////////////////////////////
  // target ports read callbacks
  //////////////////////////////////////// 
  bool apb_slave_callback_read(mb_address_type address, unsigned char* data, unsigned size);
  
  unsigned apb_slave_callback_read_dbg(mb_address_type address, unsigned char* data, unsigned size); 

 protected:
  ////////////////////////////////////////
  // target ports write callbacks
  //////////////////////////////////////// 
  bool apb_slave_callback_write(mb_address_type address, unsigned char* data, unsigned size);
  
  unsigned apb_slave_callback_write_dbg(mb_address_type address, unsigned char* data, unsigned size); 
  bool apb_slave_get_direct_memory_ptr(mb_address_type address, tlm::tlm_dmi& dmiData);   
};

