
/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2012     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/

//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file contains the PV class for SystemBridge.
//* This is a template file: You may modify this file to implement the 
//* behavior of your component. 
//* 
//* Model Builder version: 4.1beta1
//* Generated on: Apr. 14, 2015 02:53:29 PM, (user: markca)
//* Automatically merged on: Apr. 14, 2015 04:26:49 PM, (user: markca)
//* Automatically merged on: Apr. 14, 2015 04:47:14 PM, (user: markca)
//* Automatically merged on: May. 07, 2015 01:32:31 PM, (user: markca)
//* Automatically merged on: May. 07, 2015 03:19:42 PM, (user: markca)
//*>



#include "SystemBridge_pv.h"
#include <iostream>

using namespace sc_core;
using namespace sc_dt;
using namespace std;

//constructor
SystemBridge_pv::SystemBridge_pv(sc_module_name module_name) 
  : SystemBridge_pv_base(module_name) {
} 

/////////////////////////////////////////////////////////////////////////////////
// Use these functions to define the behavior of your model when there is a 
// read event on one of the registers as defined in the Model Builder form.
// These functions are called before the read callbacks on the port.
///////////////////////////////////////////////////////////////////////////////// 

// Read callback for REVS register.
// The value that this function returns, will be returned to the initiator port that requested its value.
unsigned int SystemBridge_pv::cb_read_REVS() {
  
  return REVS;
}
 

// Read callback for SPEED register.
// The value that this function returns, will be returned to the initiator port that requested its value.
unsigned int SystemBridge_pv::cb_read_SPEED() {
  
  return SPEED;
}
  

/////////////////////////////////////////////////////////////////////////////////
// Use these functions to define the behavior of your model when there is a 
// write event on one of the registers as defined in the Model Builder form.
// These functions are called before the write callbacks on the port.
///////////////////////////////////////////////////////////////////////////////// 

// Write callback for REVS register.
// The newValue has been already assigned to the REVS register.
void SystemBridge_pv::cb_write_REVS(unsigned int newValue) {
  //  cout << "SystemBridge_pv::cb_write_REVS " << newValue << endl;
}
 

// Write callback for SPEED register.
// The newValue has been already assigned to the SPEED register.
void SystemBridge_pv::cb_write_SPEED(unsigned int newValue) {
  //  cout << "SystemBridge_pv::cb_write_SPEED " << newValue << endl;  
}
  

// Read callback for m4_slave port.
// Returns true when successful.
bool SystemBridge_pv::m4_slave_callback_read(mb_address_type address, unsigned char* data, unsigned size) {
  
  return true;
}

// Write callback for m4_slave port.
// Returns true when successful.
bool SystemBridge_pv::m4_slave_callback_write(mb_address_type address, unsigned char* data, unsigned size) {
  
  return true;
} 




unsigned SystemBridge_pv::m4_slave_callback_read_dbg(mb_address_type address, unsigned char* data, unsigned size) {
  return 0;
} 

unsigned SystemBridge_pv::m4_slave_callback_write_dbg(mb_address_type address, unsigned char* data, unsigned size) {
  return 0;
} 

bool SystemBridge_pv::m4_slave_get_direct_memory_ptr(mb_address_type address, tlm::tlm_dmi& dmiData) {
  return false;
}

 
void SystemBridge_pv::cb_transport_dbg_REVS(tlm::tlm_generic_payload& trans) {}
void SystemBridge_pv::cb_transport_dbg_SPEED(tlm::tlm_generic_payload& trans) {}
