summit_begin_package v2:ui:factory

summit_package_require UI
summit_package_require v2:ui
summit_package_require v2:ui:mainwindow
summit_package_require v2:ui:filedialog
summit_package_require v2:ui:block_diagram
summit_package_require v2:ui:editdialog
summit_package_require v2:ui:projectdialog
summit_package_require v2:ui:library
summit_package_require v2:ui:filterdialog
summit_package_require v2:ui:topdialog
summit_package_require v2:ui:clockdialog
summit_package_require v2:ui:libgendialog
summit_package_require v2:ui:conffromipxact_dialog
summit_package_require v2:ui:quitsimulationdialog
summit_package_require v2:ui:simulationdialog
summit_package_require v2:ui:vpdialog
summit_package_require v2:ui:licensedialog
summit_package_require v2:ui:inspectdialog
summit_package_require v2:ui:path_variables_adder
summit_package_require v2:ui:simulation_control
summit_package_require v2:ui:tlminfradialog
summit_package_require v2:ui:trace_dialog
summit_package_require v2:ui:view_options
summit_package_require v2:ui:analysis:window
summit_package_require v2:ui:analysis_report_dialog

summit_end_package
