
/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2012     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/

//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file contains the PV class for driver.
//* This is a template file: You may modify this file to implement the 
//* behavior of your component. 
//* 
//* Model Builder version: 3.2.0RC
//* Generated on: Feb. 23, 2012 07:57:39 AM, (user: jon)
//*>


#pragma once

#include "driver_nr_model.h"

using namespace tlm;

//This class inherits from the driver_pv_base class
class driver_nr_pv : public driver_nr_pv_base {

 public:
  // Constructor
  // Do not add parameters here.
  // To add parameters - use the Model Builder form (under PV->Parameters tab)
  SC_HAS_PROCESS(driver_nr_pv);
  driver_nr_pv(sc_module_name module_name); 
  ~driver_nr_pv();

  bool y_write(mb_address_type address, unsigned int *data, unsigned size);

  void thread();
  void simple();
  void random();
};
