
/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2012     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/

//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file is write protected. 
//* DO NOT MODIFY THIS FILE.
//*
//* This file is generated according to the parameters in the 
//* Model Builder form.
//* This class contains the infrastructure to define the behavior of the component.
//* The streamTrans_pv will be derived from this class.
//*
//* Model Builder version: 3.2.0
//* Generated on: Feb. 29, 2012 03:31:58 AM, (user: jon)
//*>


#include "streamTrans_model.h"

#ifdef MODEL_BUILDER_VERSION_NUMBER
#if 320 != MODEL_BUILDER_VERSION_NUMBER
#error "This model was generated using Model Builder 3.2.0. Please regenerate model."
#endif
#else
#error "Please regenerate model."
#endif

using namespace sc_core;
using namespace sc_dt;
using namespace std;


streamTrans_pv_base::streamTrans_pv_base(sc_module_name& module_name) : 
  streamTrans_pv_base_mb_compatibility(module_name),
  VISTA_MB_PV_INIT_MEMBER(master_1),
  VISTA_MB_PV_INIT_MEMBER(slave_a),
  SD_INITIALIZE_PARAMETER(clock, sc_core::sc_time(10, sc_core::SC_NS)),
  SD_INITIALIZE_PARAMETER(generic_clock, clock),
  SD_INITIALIZE_PARAMETER(nominal_voltage, 1),
  SD_INITIALIZE_PARAMETER(mb_debug, false),
  SD_INITIALIZE_PARAMETER(verbose_parameters, true),
  SD_INITIALIZE_PARAMETER(slave_a_pipeline_length, 2),
  SD_INITIALIZE_PARAMETER(ProcessD, 3),
  SD_INITIALIZE_PARAMETER(InputD, 2),
  SD_INITIALIZE_PARAMETER(Id, 1),
  VISTA_MB_PV_INIT_MEMBER(TP1),
  VISTA_MB_PV_INIT_MEMBER(TP2),
  VISTA_MB_PV_INIT_MEMBER(m_processd),
  VISTA_MB_PV_INIT_MEMBER(processFactor) { 
  payload_on_stack = 0;

  VISTA_MB_PV_BIND_FW_PROCESS_TO_TARGET(slave_a);
  VISTA_MB_PV_BIND_BW_PROCESS_TO_MASTER(master_1);
  VISTA_MB_PV_REGISTER_SELF_FW_PROCESS_CALLBACKS(slave_a);
  VISTA_MB_PV_REGISTER_SELF_BW_PROCESS_CALLBACKS(master_1);

  if(verbose_parameters) print_parameters();
}

void streamTrans_pv_base::print_parameters()
{
  const char* name;
  if (!strcmp(this->basename(), "PV"))
    name = this->get_parent()->name();
  else
    name = this->name();

  std::cout.setf(ios::hex, ios::basefield);
  std::cout.setf(ios::showbase);
  std::cout << name << "::parameters:\n";
  std::cout << "\tclock = " << clock << "\n";
  std::cout << "\tgeneric_clock = " << generic_clock << "\n";
  std::cout << "\tnominal_voltage = " << nominal_voltage << "\n";
  std::cout << "\tmb_debug = " << mb_debug << "\n";
  std::cout << "\tverbose_parameters = " << verbose_parameters << "\n";
  std::cout << "\tslave_a_pipeline_length = " << slave_a_pipeline_length << "\n";
  std::cout << "\tProcessD = " << ProcessD << "\n";
  std::cout << "\tInputD = " << InputD << "\n";
  std::cout << "\tId = " << Id << "\n";
  std::cout.unsetf(ios::showbase);
  std::cout.setf(ios::dec, ios::basefield);
  std::cout << std::endl;
}

/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2012     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/

//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file is write protected.
//* DO NOT MODIFY THIS FILE.
//*
//* This file is used only for learning the component.
//* It contains the machine architecture class for your streamTrans model.
//* 
//* Model Builder version: 3.2.0
//* Generated on: Feb. 29, 2012 03:31:59 AM, (user: jon)
//*>

#include "streamTrans_model.h"
#include "model_builder.h"

using namespace ::mb::utl::minmax;

streamTrans_machine_arch::streamTrans_machine_arch()
    : MachineArch(2, 4) {
        sc_dt::uint64* values = m_values;
        TP1.getSingleVariableAtIndex(0).setValuePtr(values);
        TP2.getSingleVariableAtIndex(0).setValuePtr(values);
        m_processd.getSingleVariableAtIndex(0).setValuePtr(values);
        processFactor.getSingleVariableAtIndex(0).setValuePtr(values);
        
        reset();
    }
    
    ////////////////////////////////////////////////////////////////////
    //   function for port: slave_a
    ////////////////////////////////////////////////////////////////////
    
    
    //////
    // functions for port: slave_a, transaction: READ
    //////
    
    void streamTrans_machine_arch::transaction_instance__slave_a__READ
      (
        sc_dt::uint64 address,
        sc_dt::uint64 size,
        sc_dt::uint64 data, 
        bool has_been_error, 
        sc_dt::uint64 currentTime
      )
    {
      
    }
    
    //////
    // functions for port: slave_a, transaction: WRITE
    //////
    
    void streamTrans_machine_arch::transaction_instance__slave_a__WRITE
      (
        sc_dt::uint64 address,
        sc_dt::uint64 size,
        sc_dt::uint64 data, 
        bool has_been_error, 
        sc_dt::uint64 currentTime
      )
    {
      
    }
    
    ////////////////////////////////////////////////////////////////////
    //   function for port: master_1
    ////////////////////////////////////////////////////////////////////
    
    
    //////
    // functions for port: master_1, transaction: READ
    //////
    
    void streamTrans_machine_arch::transaction_instance__master_1__READ
      (
        sc_dt::uint64 address,
        sc_dt::uint64 size,
        sc_dt::uint64 data, 
        bool has_been_error, 
        sc_dt::uint64 currentTime
      )
    {
      
    }
    
    //////
    // functions for port: master_1, transaction: WRITE
    //////
    
    void streamTrans_machine_arch::transaction_instance__master_1__WRITE
      (
        sc_dt::uint64 address,
        sc_dt::uint64 size,
        sc_dt::uint64 data, 
        bool has_been_error, 
        sc_dt::uint64 currentTime
      )
    {
      
    }

void streamTrans_machine_arch::startTransaction(unsigned portIndex, unsigned transactionIndex, sc_dt::uint64 currentTime) {
  switch(portIndex) {
    case(0) : break;
    case(1) : break;
    default: break;
  }
}
VariableBase* streamTrans_machine_arch::getVariableBasePtrByName(const char* name) {
  if (!strcmp(name, "TP1")) {
    return &TP1;
  }
  if (!strcmp(name, "TP2")) {
    return &TP2;
  }
  if (!strcmp(name, "m_processd")) {
    return &m_processd;
  }
  if (!strcmp(name, "processFactor")) {
    return &processFactor;
  }
  return NULL;
}
Register* streamTrans_machine_arch::getRegisterByName(const char* name) {
  return 0;
}
void streamTrans_machine_arch::reset() { 
    MachineArch::reset();
}
bool streamTrans_machine_arch::getAddressRange(unsigned portIndex, sc_dt::uint64& begin, sc_dt::uint64& end) {
    switch(portIndex) {
        case(0) :   return false;
        case(1) :   return false;
        default: break;
    }
    return false; 
}
void streamTrans_machine_arch::callTransaction(unsigned portIndex, unsigned transactionIndex, sc_dt::uint64 address, sc_dt::uint64 size, sc_dt::uint64 data, bool has_been_error, sc_dt::uint64 currentTime) {
    switch(portIndex) {
        case(0) : { //port: slave_a
            switch(transactionIndex) {
                case(0) : { //transaction: READ
                    this->transaction_instance__slave_a__READ
                      (
                        address, 
                        size, 
                        data, 
                        has_been_error, 
                        currentTime
                      );
                    break;
                }
                case(1) : { //transaction: WRITE
                    this->transaction_instance__slave_a__WRITE
                      (
                        address, 
                        size, 
                        data, 
                        has_been_error, 
                        currentTime
                      );
                    break;
                }
            }
            break;
        }
        case(1) : { //port: master_1
            switch(transactionIndex) {
                case(0) : { //transaction: READ
                    this->transaction_instance__master_1__READ
                      (
                        address, 
                        size, 
                        data, 
                        has_been_error, 
                        currentTime
                      );
                    break;
                }
                case(1) : { //transaction: WRITE
                    this->transaction_instance__master_1__WRITE
                      (
                        address, 
                        size, 
                        data, 
                        has_been_error, 
                        currentTime
                      );
                    break;
                }
            }
            break;
        }
        default: break;
    }
}


/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2012     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/

//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file is write protected. 
//* DO NOT MODIFY THIS FILE.
//*
//* This file is generated according to the parameters in the 
//* Model Builder form.
//* 
//* Any change in parameters, policies, ports, protocols, etc. will change this file
//* upon generation of the timing model (using generate_timing_model command).
//* The streamTrans_t will be derived from this class.
//*
//* Model Builder version: 3.2.0
//* Generated on: Feb. 29, 2012 03:31:59 AM, (user: jon)
//*>




#include "streamTrans_model.h"
#include <math.h>
#include <stdlib.h>

using namespace esl::tlm_sim;
using namespace esl::sc_sim;
using namespace std;
using namespace sc_dt;
using namespace sc_core;


void streamTrans_t_base::schedule_generic_READ
(long port_index,
 sc_dt::uint64 delay,
 long& transactionSize,
 esl::include::transaction_power& power , long ADDR, long* rDATA, long PRIORITY, long BURST, long SIZE, long STATUS) {
  sc_dt::uint64 local_address = 0;
  local_address = ADDR,
  scheduleGenericTransaction(port_index,
                             0,
                             local_address,
                             (unsigned char*)rDATA,
                             transactionSize,
                             SIZE,
                             0, papoulis::getSimulationTime() + delay,
                             0,
                             0);
}

void streamTrans_t_base::schedule_generic_WRITE
(long port_index,
 sc_dt::uint64 delay,
 long& transactionSize,
 esl::include::transaction_power& power , long ADDR, long* wDATA, long PRIORITY, long BURST, long SIZE, long STATUS) {
  sc_dt::uint64 local_address = 0;
  local_address = ADDR,
  scheduleGenericTransaction(port_index,
                             1,
                             local_address,
                             (unsigned char*)wDATA,
                             transactionSize,
                             SIZE,
                             0, papoulis::getSimulationTime() + delay,
                             0,
                             0);
}



void streamTrans_t_base::start_transaction_generic_READ
(esl::include::TRequest* request,
 unsigned port_index,
 sc_dt::uint64 startTime,
 sc_dt::uint64 endTime,
 sc_dt::uint64* parameters,
 bool hasBeenError) {
  
  long burstSize = request->getSize();
  parameters[0] = request->getAddress();
  parameters[1] = request->getFirstDataBlock();
  parameters[4] = request->getBlockSize();
  
  this->getMachineArch()->startTransaction(port_index,
                                           0,
                                           startTime);
  
  this->accept_generic_READ
    (port_index, 
     startTime, 
     burstSize, 
     parameters[0], 
     parameters[1], 
     parameters[2], 
     parameters[3], 
     parameters[4], 
     parameters[5]);
}

void streamTrans_t_base::end_transaction_generic_READ
(esl::include::TRequest* request,
 unsigned port_index,
 sc_dt::uint64 startTime,
 sc_dt::uint64 endTime,
 sc_dt::uint64* parameters,
 bool hasBeenError) {
  long burstSize = request->getSize();
  parameters[0] = request->getAddress();
  parameters[1] = request->getFirstDataBlock();
  parameters[4] = request->getBlockSize();                                                                         
  this->getMachineArch()->callTransaction(port_index, 
                                          0, 
                                          request->getAddress(),
                                          burstSize,
                                          request->getFirstDataBlock(),
                                          hasBeenError,
                                          startTime);
  
  this->end_generic_READ
    (port_index,
     endTime,
     burstSize,
     parameters[0],
     parameters[1],
     parameters[2],
     parameters[3],
     parameters[4],
     parameters[5]);
}
void streamTrans_t_base::start_transaction_generic_WRITE
(esl::include::TRequest* request,
 unsigned port_index,
 sc_dt::uint64 startTime,
 sc_dt::uint64 endTime,
 sc_dt::uint64* parameters,
 bool hasBeenError) {
  
  long burstSize = request->getSize();
  parameters[0] = request->getAddress();
  parameters[1] = request->getFirstDataBlock();
  parameters[4] = request->getBlockSize();
  
  this->getMachineArch()->startTransaction(port_index,
                                           1,
                                           startTime);
  
  this->accept_generic_WRITE
    (port_index, 
     startTime, 
     burstSize, 
     parameters[0], 
     parameters[1], 
     parameters[2], 
     parameters[3], 
     parameters[4], 
     parameters[5]);
}

void streamTrans_t_base::end_transaction_generic_WRITE
(esl::include::TRequest* request,
 unsigned port_index,
 sc_dt::uint64 startTime,
 sc_dt::uint64 endTime,
 sc_dt::uint64* parameters,
 bool hasBeenError) {
  long burstSize = request->getSize();
  parameters[0] = request->getAddress();
  parameters[1] = request->getFirstDataBlock();
  parameters[4] = request->getBlockSize();                                                                         
  this->getMachineArch()->callTransaction(port_index, 
                                          1, 
                                          request->getAddress(),
                                          burstSize,
                                          request->getFirstDataBlock(),
                                          hasBeenError,
                                          startTime);
  
  this->end_generic_WRITE
    (port_index,
     endTime,
     burstSize,
     parameters[0],
     parameters[1],
     parameters[2],
     parameters[3],
     parameters[4],
     parameters[5]);
}

streamTrans_t_base::TransactionCallbackFunctionPointer streamTrans_t_base::getTransactionCallback(unsigned callbackIndex) {
  static TransactionCallbackFunctionPointer funcArray[] = {
    static_cast<TransactionCallbackFunctionPointer>(&streamTrans_t_base::start_transaction_generic_READ),
    static_cast<TransactionCallbackFunctionPointer>(&streamTrans_t_base::start_transaction_generic_WRITE),
    static_cast<TransactionCallbackFunctionPointer>(&streamTrans_t_base::start_transaction_generic_READ),
    static_cast<TransactionCallbackFunctionPointer>(&streamTrans_t_base::start_transaction_generic_WRITE),
    static_cast<TransactionCallbackFunctionPointer>(&streamTrans_t_base::end_transaction_generic_READ),
    static_cast<TransactionCallbackFunctionPointer>(&streamTrans_t_base::end_transaction_generic_WRITE),
    static_cast<TransactionCallbackFunctionPointer>(&streamTrans_t_base::end_transaction_generic_READ),
    static_cast<TransactionCallbackFunctionPointer>(&streamTrans_t_base::end_transaction_generic_WRITE),
    0
  };
  if(callbackIndex >= sizeof(funcArray) / sizeof(*funcArray) - 1)
    return 0;
  return funcArray[callbackIndex];
}




streamTrans_t_base::streamTrans_t_base(sc_module_name& module_name, long simulation) :
  papoulis::SystemCBaseModel(module_name),
  m_machineArch(new streamTrans_machine_arch()),
  SD_INITIALIZE_PARAMETER(clock, sc_core::sc_time(10, sc_core::SC_NS)),
  SD_INITIALIZE_PARAMETER(generic_clock, clock),
  SD_INITIALIZE_PARAMETER(nominal_voltage, 1),
  SD_INITIALIZE_PARAMETER(mb_debug, false),
  SD_INITIALIZE_PARAMETER(verbose_parameters, true),
  SD_INITIALIZE_PARAMETER(slave_a_pipeline_length, 2),
  SD_INITIALIZE_PARAMETER(ProcessD, 3),
  SD_INITIALIZE_PARAMETER(InputD, 2),
  SD_INITIALIZE_PARAMETER(Id, 1),
  m_simulation(simulation),
  TP1("TP1", this),
  TP2("TP2", this),
  m_processd("m_processd", this),
  processFactor("processFactor", this)
{
  bool separate_read_channel = false;
  bool separate_write_channel = false;
  fix_clock_parameter(generic_clock, "generic_clock");
  separate_read_channel = false;
  separate_write_channel = false;
  port_descriptions[slave_a].port_name = "slave_a";
  port_descriptions[slave_a].port_kind = PortDescription::READ_WRITE_CHANNEL_PORT;
  if (separate_write_channel && separate_read_channel)
    port_descriptions[slave_a].port_kind = PortDescription::SEPARATE_READ_WRIE_CHANNEL_PORT;
  port_descriptions[slave_a].is_read_write_address_channel = 0;
  
  port_descriptions[slave_a].is_read_write_address_channel = 1;
  port_descriptions[slave_a].is_master_port = 0;
  port_descriptions[slave_a].is_signal_port = 0;
  port_descriptions[slave_a].port_width = 4;
  port_descriptions[slave_a].protocol_name = "generic";
  port_descriptions[slave_a].params_count = 10;
  port_descriptions[slave_a].clock = generic_clock;
  m_machineArch->configureClock(slave_a, mb::sysc::sc_time_to_ps(generic_clock));
  port_descriptions[slave_a].add_read_phase(tlm::tlm_phase(tlm::BEGIN_REQ), !0, 1);
  port_descriptions[slave_a].add_read_phase(tlm::tlm_phase(tlm::BEGIN_RESP), !1, 1);

  fix_clock_parameter(generic_clock, "generic_clock");
  separate_read_channel = false;
  separate_write_channel = false;
  port_descriptions[master_1].port_name = "master_1";
  port_descriptions[master_1].port_kind = PortDescription::READ_WRITE_CHANNEL_PORT;
  if (separate_write_channel && separate_read_channel)
    port_descriptions[master_1].port_kind = PortDescription::SEPARATE_READ_WRIE_CHANNEL_PORT;
  port_descriptions[master_1].is_read_write_address_channel = 0;
  
  port_descriptions[master_1].is_read_write_address_channel = 1;
  port_descriptions[master_1].is_master_port = 1;
  port_descriptions[master_1].is_signal_port = 0;
  port_descriptions[master_1].port_width = 4;
  port_descriptions[master_1].protocol_name = "generic";
  port_descriptions[master_1].params_count = 10;
  port_descriptions[master_1].clock = generic_clock;
  m_machineArch->configureClock(master_1, mb::sysc::sc_time_to_ps(generic_clock));
  port_descriptions[master_1].add_read_phase(tlm::tlm_phase(tlm::BEGIN_REQ), !1, 1);
  port_descriptions[master_1].add_read_phase(tlm::tlm_phase(tlm::BEGIN_RESP), !0, 1);


  port_descriptions[slave_a].default_read_transaction_name = "READ";
  port_descriptions[master_1].default_read_transaction_name = "READ";
  port_descriptions[slave_a].default_write_transaction_name = "WRITE";
  port_descriptions[master_1].default_write_transaction_name = "WRITE";

  fix_internal_clock_parameter(clock, "clock");
  set_ports(mb::sysc::sc_time_to_ps(clock), port_count, port_descriptions);

  bool isCpu = false;
  
  esl::tlm_sim::UserRunningModel* userRunningModel = Papoulis_CreateUserRunningModel(name(),
                                                                                     0,
                                                                                     this,
                                                                                     simulation,
                                                                                     false,
                                                                                     isCpu);
  setUserRunningModel(userRunningModel);
  set_nominal_voltage(nominal_voltage);
  set_sync_all(0);
  set_sync_all(0);
  
  
  
  unsigned sequential_policy_index = 0;
  sequential_policy* sequential_policy_handle = 0;
  user_sequential_policy_descriptions[sequential_policy_index].firstTransaction = "TP1.write";
  user_sequential_policy_descriptions[sequential_policy_index].secondTransaction = "TP2.write";
  user_sequential_policy_descriptions[sequential_policy_index].latency = m_processd;
  user_sequential_policy_descriptions[sequential_policy_index].syncMode = mb::tlm20::SYNC_BEGIN;
  sequential_policy_handle = new sequential_policy(userRunningModel, user_sequential_policy_descriptions[sequential_policy_index]);
  m_sequential_vector.push_back(sequential_policy_handle);
  sequential_policy_handle->set_power(0);
  sequential_policy_index++;
  set_user_sequential_policies(user_sequential_policy_count, user_sequential_policy_descriptions);
  
  

  
  

  delay_policy* delay_policy_handle = 0;

  delay_policy_handle = new delay_policy(userRunningModel,
                                         "slave_a",
                                         0,
                                         InputD,
                                         mb::tlm20::SYNC_BEGIN);
  delay_policy_handle->set_power(0);
  m_delay_vector.push_back(delay_policy_handle);

  

  constant_global_power_policy* p = new constant_global_power_policy(userRunningModel);
  
  
  set_nominal_clock(1000000/100); /* in ps */ 
  update_coefficients();
  set_global_power_policy(p);
}

void streamTrans_t_base::update_sync_all() {
  set_sync_all(0);
  set_sync_all(0);
}

void streamTrans_t_base::update_pipeline_parameters(esl::sc_sim::pipeline_policy* handle) {
  if (m_pipeline_vector.size() == 0)
    return;


}

void streamTrans_t_base::update_sequential_parameters(esl::sc_sim::sequential_policy* handle) {
  if (m_sequential_vector.size() == 0)
    return;

  if (handle == m_sequential_vector[0]) {
    handle->setLatency(m_processd);
    handle->setSyncMode(mb::tlm20::SYNC_BEGIN);
    handle->set_power(0);
    return;
  }
}

void streamTrans_t_base::update_delay_parameters(esl::sc_sim::delay_policy* handle) {
  if (m_delay_vector.size() == 0)
    return;

  if (handle == m_delay_vector[0]) {
    handle->set_inner_delay(0);
    handle->set_start_delay(InputD);
    handle->setSyncMode(mb::tlm20::SYNC_BEGIN);
    handle->set_power(0);
    return;
  }
}

void streamTrans_t_base::update_bus_parameters(esl::sc_sim::uniform_bus_policy* handle) {
  if (m_bus_vector.size() == 0)
    return;

}

void streamTrans_t_base::update_power_parameters(esl::sc_sim::power_policy* handle) {
  if (m_power_vector.size() == 0)
    return;

}

void streamTrans_t_base::update_state_power_parameters(esl::sc_sim::state_power_policy* handle) {
  if (m_state_power_vector.size() == 0)
    return;

}


bool streamTrans_t_base::triggerRegistersGotHit(unsigned portIndex, tlm::tlm_generic_payload& trans) {
  mb::utl::Segment<uint64_t> transactionRange(trans.get_address(), trans.get_address() + trans.get_data_length());

  return false;
}

bool streamTrans_t_base::portHasRegisters(unsigned portIndex) {
  switch (portIndex) {

  }
  return false;
}


/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2012     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/

//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file is write protected.
//* DO NOT MODIFY THIS FILE.
//*
//* This file contains the PVT class for streamTrans.
//* It connects between the PV and T models.
//* Your top-level design should instantiate this model.
//* 
//* In order to synchronize the activty between the PV and the T models, every 
//* PV transaction is monitored and queued in the T sync ports.
//* Whenever a synchronization point is reached, the T models are executed and 
//* the corresponding T transactions are launched.
//* A synchronization point is reached whenever there is a wait statement on a testbench thread. 
//*
//* Model Builder version: 3.2.0
//* Generated on: Feb. 29, 2012 03:31:59 AM, (user: jon)
//*>

#include "streamTrans_model.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


#include "streamTrans_pv.h"

// Constructor
streamTrans_pvt::streamTrans_pvt(sc_module_name module_name)
  : esl::sc_sim::PVTBaseModel(module_name, 0),
    streamTrans_pvt_param_defaults(this->name()),
    master_1("master_1"),
    slave_a("slave_a"), 
    master_1_entry("unvisible_master_1_entry"),
    slave_a_entry("unvisible_slave_a_entry"),
    m_master_1_nb_connector(*this),
    m_slave_a_nb_connector(*this)
{
  m_streamTrans_t = streamTrans_t_base::create_t("T", 1);
  m_streamTrans_pv = new streamTrans_pv("PV");
  bind();
}

streamTrans_pvt::~streamTrans_pvt() {
  delete m_streamTrans_t; delete m_streamTrans_pv;
}



void streamTrans_pvt::bind()
{
  /* connect pv to entry ports */
  
  
  getPV()->master_1.bind(master_1_entry);
  slave_a_entry.bind(getPV()->slave_a);   

  /* set callbacks on external and entry ports */ 

  slave_a.b_transport_cb.set(&slave_a_entry, &slave_a_entry_type::b_transport);
  slave_a.transport_dbg_cb.set(&slave_a_entry, &slave_a_entry_type::transport_dbg);
  slave_a.get_direct_mem_ptr_cb.set(&slave_a_entry, &slave_a_entry_type::get_direct_mem_ptr);

  master_1_entry.b_transport_cb.set(this, &self_type::b_transport_outside_master_1);
  master_1_entry.transport_dbg_cb.set(&master_1, &master_1_type::transport_dbg);
  master_1_entry.get_direct_mem_ptr_cb.set(&master_1, &master_1_type::get_direct_mem_ptr);

  
  /* connect t non blocking callbacks */

  master_1.nb_transport_bw_cb.set(this, &self_type::receive_nb_transport_master_1);
  getT()->set_port_cb(1, &m_master_1_nb_connector);

  slave_a.nb_transport_fw_cb.set(this, &self_type::receive_nb_transport_slave_a);
  getT()->set_port_cb(0, &m_slave_a_nb_connector);

  slave_a_entry.invalidate_direct_mem_ptr_cb.set(&slave_a, &slave_a_type::invalidate_direct_mem_ptr);

  master_1.invalidate_direct_mem_ptr_cb.set(&master_1_entry, &master_1_entry_type::invalidate_direct_mem_ptr);

}



void streamTrans_pvt::b_transport_outside_master_1(tlm::tlm_generic_payload& p, sc_core::sc_time& t)
{
   
  master_1.b_transport(p, t);
  
}
