
/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2015     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/

//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file contains the PV class for extIn.
//* This is a template file: You may modify this file to implement the 
//* behavior of your component. 
//* 
//* Model Builder version: 3.5.0
//* Generated on: Jan. 08, 2013 08:17:04 AM, (user: jon)
//* Automatically merged on: Nov. 24, 2015 07:25:37 AM, (user: jon)
//*>


#pragma once

#include "extIn_model.h"

using namespace tlm;

//This class inherits from the extIn_pv_base class
class extIn_pv : public extIn_pv_base {

 public:
  // Constructor
  // Do not add parameters here.
  // To add parameters - use the Model Builder form (under PV->Parameters tab)
  SC_HAS_PROCESS(extIn_pv);
  extIn_pv(sc_module_name module_name); 
  ~extIn_pv();

  void thread();
  void simple();
  void random();
};
