
/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2012     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/

//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file contains the PV class for FPGA_I2C_custom.
//* This is a template file: You may modify this file to implement the 
//* behavior of your component. 
//* 
//* Model Builder version: 4.1beta1
//* Generated on: Mar. 12, 2015 03:13:17 PM, (user: markca)
//* Automatically merged on: Jun. 05, 2015 03:47:25 PM, (user: markca)
//* Automatically merged on: Jul. 10, 2015 02:58:19 PM, (user: markca)
//* Automatically merged on: Jul. 10, 2015 03:46:05 PM, (user: markca)
//* Automatically merged on: Jul. 10, 2015 09:48:22 PM, (user: markca)
//* Automatically merged on: Jul. 13, 2015 10:41:38 AM, (user: markca)
//* Automatically merged on: Jul. 13, 2015 11:33:34 AM, (user: markca)
//* Automatically merged on: Jul. 13, 2015 11:43:31 AM, (user: markca)
//* Automatically merged on: Jul. 13, 2015 11:55:24 AM, (user: markca)
//* Automatically merged on: Jul. 13, 2015 11:58:54 AM, (user: markca)
//*>


#pragma once

#include "FPGA_I2C_custom_model.h"

using namespace tlm;

//This class inherits from the FPGA_I2C_custom_pv_base class
class FPGA_I2C_custom_pv : public FPGA_I2C_custom_pv_base {
 public:
  typedef esl::tlm_types::Address mb_address_type;
  int state;
  int size_state;
  bool resender;
  unsigned int ifp_size;
  FILE *ifp;

 public:
  // Constructor
  // Do not add parameters here.
  // To add parameters - use the Model Builder form (under PV->Parameters tab)
  SC_HAS_PROCESS(FPGA_I2C_custom_pv);
  FPGA_I2C_custom_pv(sc_core::sc_module_name module_name);    

 protected:
  ////////////////////////////////////////
  // target ports read callbacks
  //////////////////////////////////////// 
  bool slave_callback_read(mb_address_type address, unsigned char* data, unsigned size);
  
  unsigned slave_callback_read_dbg(mb_address_type address, unsigned char* data, unsigned size); 

 protected:
  ////////////////////////////////////////
  // target ports write callbacks
  //////////////////////////////////////// 
  bool slave_callback_write(mb_address_type address, unsigned char* data, unsigned size);
  
  unsigned slave_callback_write_dbg(mb_address_type address, unsigned char* data, unsigned size);  
  bool slave_get_direct_memory_ptr(mb_address_type address, tlm::tlm_dmi& dmiData);   
};

