
/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2012     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/

//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file contains the PV class for FPGA_SPI_custom.
//* This is a template file: You may modify this file to implement the 
//* behavior of your component. 
//* 
//* Model Builder version: 4.1beta1
//* Generated on: Mar. 13, 2015 02:12:49 PM, (user: markca)
//* Automatically merged on: Jun. 05, 2015 03:47:25 PM, (user: markca)
//*>



#include "FPGA_SPI_custom_pv.h"
#include <iostream>

using namespace sc_core;
using namespace sc_dt;
using namespace std;

//constructor
FPGA_SPI_custom_pv::FPGA_SPI_custom_pv(sc_module_name module_name) 
  : FPGA_SPI_custom_pv_base(module_name) {
}      

// Read callback for slave port.
// Returns true when successful.
bool FPGA_SPI_custom_pv::slave_callback_read(mb_address_type address, unsigned char* data, unsigned size) {

  *data = (unsigned int) 0x11223344;
  cout << name() << " @ " << sc_time_stamp() << " address : " << hex << address << " READ, sending: " << (unsigned int) (*data) << endl;

  return true;
}

// Write callback for slave port.
// Returns true when successful.
bool FPGA_SPI_custom_pv::slave_callback_write(mb_address_type address, unsigned char* data, unsigned size) {

  cout << name() << " @ " << sc_time_stamp() << " address : " << hex << address << " WRITE " << (unsigned int) (*data) << endl;
  
  return true;
} 




unsigned FPGA_SPI_custom_pv::slave_callback_read_dbg(mb_address_type address, unsigned char* data, unsigned size) {
  return 0;
} 

unsigned FPGA_SPI_custom_pv::slave_callback_write_dbg(mb_address_type address, unsigned char* data, unsigned size) {
  return 0;
} 

bool FPGA_SPI_custom_pv::slave_get_direct_memory_ptr(mb_address_type address, tlm::tlm_dmi& dmiData) {
  return false;
}

 
