
/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2012     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/

//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file contains the PV class for ABSDriver.
//* This is a template file: You may modify this file to implement the 
//* behavior of your component. 
//* 
//* Model Builder version: 4.1beta2
//* Generated on: Apr. 28, 2015 09:48:17 AM, (user: jon)
//* Automatically merged on: May. 13, 2015 12:44:20 PM, (user: jon)
//*>

extern bool myRunning;

#include "ABSDriver_pv.h"
#include <iostream>

using namespace sc_core;
using namespace sc_dt;
using namespace std;

//constructor
ABSDriver_pv::ABSDriver_pv(sc_module_name module_name) 
  : ABSDriver_pv_base(module_name) {

}    

// Read callback for rxi port.
// Returns true when successful.
bool ABSDriver_pv::rxi_callback_read(mb_address_type address, unsigned char* data, unsigned size) {
  
  return true;
}

// Write callback for rxi port.
// Returns true when successful.
bool ABSDriver_pv::rxi_callback_write(mb_address_type address, unsigned char* data, unsigned size) {
  
  return true;
} 

unsigned ABSDriver_pv::rxi_callback_read_dbg(mb_address_type address, unsigned char* data, unsigned size) {
  return 0;
} 

unsigned ABSDriver_pv::rxi_callback_write_dbg(mb_address_type address, unsigned char* data, unsigned size) {
  return 0;
} 

bool ABSDriver_pv::rxi_get_direct_memory_ptr(mb_address_type address, tlm::tlm_dmi& dmiData) {
  return false;
}

// callback for any change in signal: rxi of type: sc_in<bool>
/*void ABSDriver_pv::rxi_callback() {
  unsigned d;
  mb::mb_token_ptr tokenptr;

  while(myRunning) {
    wait (70, SC_MS);
    d = s->pull();
    tokenptr = new mb::mb_token();
    tokenptr->setField("CreationTime", sc_time_stamp());
    set_current_token(tokenptr);
    m_write(CAN_DATA, d);
    m_write(CAN_SIZE, 4);
    m_write(CAN_IDENT, m_SPEEDID);
  }
}
*/

 
