
/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2012     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/

//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file contains the PV class for EMUDriver.
//* This is a template file: You may modify this file to implement the 
//* behavior of your component. 
//* 
//* Model Builder version: 3.9.0
//* Generated on: Mar. 31, 2015 03:29:12 PM, (user: jon)
//* Automatically merged on: May. 13, 2015 12:42:16 PM, (user: jon)
//*>


#pragma once

#include "EMUDriver_model.h"

using namespace tlm;

//This class inherits from the EMUDriver_pv_base class
class EMUDriver_pv : public EMUDriver_pv_base {
 public:
  typedef esl::tlm_types::Address mb_address_type;
 public:
  // Constructor
  // Do not add parameters here.
  // To add parameters - use the Model Builder form (under PV->Parameters tab)
  SC_HAS_PROCESS(EMUDriver_pv);
  EMUDriver_pv(sc_core::sc_module_name module_name);   

  void thread();

 protected:
  ////////////////////////////////////////
  // target ports read callbacks
  //////////////////////////////////////// 
  bool rxi_callback_read(mb_address_type address, unsigned char* data, unsigned size);
  
  unsigned rxi_callback_read_dbg(mb_address_type address, unsigned char* data, unsigned size); 

 protected:
  ////////////////////////////////////////
  // target ports write callbacks
  //////////////////////////////////////// 
  bool rxi_callback_write(mb_address_type address, unsigned char* data, unsigned size);
  
  unsigned rxi_callback_write_dbg(mb_address_type address, unsigned char* data, unsigned size);  
  bool rxi_get_direct_memory_ptr(mb_address_type address, tlm::tlm_dmi& dmiData);   
};

