
/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2012     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/

//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file contains the PV class for RadioDriver.
//* This is a template file: You may modify this file to implement the 
//* behavior of your component. 
//* 
//* Model Builder version: 3.9.0
//* Generated on: Mar. 31, 2015 03:10:09 PM, (user: jon)
//* Automatically merged on: May. 07, 2015 01:44:00 PM, (user: markca)
//* Automatically merged on: May. 07, 2015 03:27:52 PM, (user: markca)
//*>



#include "RadioDriver_pv.h"
#include <iostream>

using namespace sc_core;
using namespace sc_dt;
using namespace std;

//constructor
RadioDriver_pv::RadioDriver_pv(sc_module_name module_name) 
  : RadioDriver_pv_base(module_name) {
}    

 

// callback for any change in signal: rxi of type: sc_in<bool>
void RadioDriver_pv::rxi_callback() {
}
