
/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2015     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/

//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file contains the PV class for NADA.
//* This is a template file: You may modify this file to implement the 
//* behavior of your component. 
//* 
//* Model Builder version: 4.2.1
//* Generated on: Nov. 15, 2016 01:30:43 PM, (user: markca)
//*>



#include "NADA_pv.h"
#include <iostream>

using namespace sc_core;
using namespace sc_dt;
using namespace std;

//constructor
NADA_pv::NADA_pv(sc_module_name module_name) 
  : NADA_pv_base(module_name) {
  //SC_THREAD(thread);
}      

 

// in order to minimize merging conflicts, we recommend to add your functions after this comment

void NADA_pv::thread() {
  wait(2, SC_SEC);
  unsigned int data = 0x1;
  cout << sc_time_stamp() << name() << endl;
  master_write(0x0, &data, 1);
}
