//----------------------------------------------------------------------
//   THIS IS AUTOMATICALLY GENERATED CODE
//   Generated by Mentor Graphics' Register Assistant V@PRODUCT_VERSION@
//----------------------------------------------------------------------
// Project         : @PROJECT_NAME@
// File            : @FILE_NAME@
//----------------------------------------------------------------------
// Created by      : @USER@
// Creation Date   : @CREATION_DATE@
//----------------------------------------------------------------------
// Title           : @PROJECT_TITLE@
//
// Description     : @PROJECT_DESCRIPTION@
//
//----------------------------------------------------------------------

#ifndef _@FILE_NO_EXTENSION_UPPER@_H
#define _@FILE_NO_EXTENSION_UPPER@_H

@GENERATED_INCLUDES@

/************************ DEFINE ACCESS RIGHTS ************************/
@GENERATED_SW_ACCESS_RIGHT_DEFINES@

/********************** DEFINE READ/WRITE MACROS **********************/
@GENERATED_READ_WRITE_DEFINES@

/********************** DEFINE HIERARCHY LEVELS ***********************/
@GENERATED_BLOCKS_STRUCTS@

/************************* DECLARE TOP ADDRESS ************************/
#define TOP__BASE 0x0

/**************************** DEFINE FIELDS ***************************/

@GENERATED_FIELDS_DEFINES@

#endif // _@FILE_NO_EXTENSION_UPPER@_H
