
/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2012     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/

//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file contains the PV class for controller.
//* This is a template file: You may modify this file to implement the 
//* behavior of your component. 
//* 
//* Model Builder version: 3.8.1RND2
//* Generated on: Jul. 24, 2014 01:01:43 PM, (user: markca)
//* Automatically merged on: Jul. 24, 2014 01:02:40 PM, (user: markca)
//* Automatically merged on: Jul. 24, 2014 06:00:40 PM, (user: markca)
//* Automatically merged on: Jul. 24, 2014 06:33:21 PM, (user: markca)
//*>


#pragma once

#include "controller_model.h"

using namespace tlm;

//This class inherits from the controller_pv_base class
class controller_pv : public controller_pv_base {
 public:
  typedef esl::tlm_types::Address mb_address_type;
 public:
  // Constructor
  // Do not add parameters here.
  // To add parameters - use the Model Builder form (under PV->Parameters tab)
  SC_HAS_PROCESS(controller_pv);
  controller_pv(sc_core::sc_module_name module_name); 

 protected:
  ////////////////////////////////////////
  // read callbacks of registers
  ////////////////////////////////////////// 
  unsigned int cb_read_BUTTON_X();
  unsigned int cb_read_BUTTON_Y();
  unsigned int cb_read_BUTTON_Z(); 
  
 protected:
  /////////////////////////////////////////
  // write callbacks of registers
  ////////////////////////////////////////// 
  void cb_write_BUTTON_X(unsigned int newValue);
  void cb_write_BUTTON_Y(unsigned int newValue);
  void cb_write_BUTTON_Z(unsigned int newValue); 

  void server_thread();

 protected:
  ////////////////////////////////////////
  // target ports read callbacks
  //////////////////////////////////////// 
  bool slave_callback_read(mb_address_type address, unsigned char* data, unsigned size);
  
  unsigned slave_callback_read_dbg(mb_address_type address, unsigned char* data, unsigned size); 

 protected:
  ////////////////////////////////////////
  // target ports write callbacks
  //////////////////////////////////////// 
  bool slave_callback_write(mb_address_type address, unsigned char* data, unsigned size);
  
  unsigned slave_callback_write_dbg(mb_address_type address, unsigned char* data, unsigned size); 
  virtual void cb_transport_dbg_BUTTON_X(tlm::tlm_generic_payload& trans);
  virtual void cb_transport_dbg_BUTTON_Y(tlm::tlm_generic_payload& trans);
  virtual void cb_transport_dbg_BUTTON_Z(tlm::tlm_generic_payload& trans); 
  bool slave_get_direct_memory_ptr(mb_address_type address, tlm::tlm_dmi& dmiData);   
};

