
/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2012     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/

//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file contains the PV class for fake_cpu.
//* This is a template file: You may modify this file to implement the 
//* behavior of your component. 
//* 
//* Model Builder version: 3.5.0
//* Generated on: Dec. 17, 2012 03:07:02 PM, (user: markca)
//*>


#pragma once
#include "fake_cpu_model.h"

using namespace tlm;

//This class inherits from the fake_cpu_pv_base class
class fake_cpu_pv : public fake_cpu_pv_base {

 public:
  // Constructor
  // Do not add parameters here.
  // To add parameters - use the Model Builder form (under PV->Parameters tab)
  SC_HAS_PROCESS(fake_cpu_pv);
  fake_cpu_pv(sc_module_name module_name);

  void print_UART0(char *ptr);

 protected:
  // SC_THREAD created for CPU
  void thread();    
    
};


